CREATE TABLE TB_VENDEDOR (
    CODIGO NUMERIC(10),
    CPF_CNPJ VARCHAR(14),
    NOME VARCHAR(50)
);

CREATE TABLE TB_COBRANCA (
    CODIGO BIGINT PRIMARY KEY,
    VALOR NUMERIC(12, 2),
    CODIGO_VENDEDOR NUMERIC(10)
);

INSERT INTO TB_VENDEDOR (CODIGO, CPF_CNPJ, NOME) VALUES (1, '00199054602', 'ARTHUR');
INSERT INTO TB_COBRANCA (CODIGO, VALOR, CODIGO_VENDEDOR) VALUES (1, 1.0, 1);