CREATE TABLE TB_VENDEDOR (
    CPF_CNPJ VARCHAR(14),
    NOME VARCHAR(50)
);

CREATE TABLE TB_COBRANCA (
    CODIGO BIGINT PRIMARY KEY,
    VALOR NUMERIC(12, 2)
);

INSERT INTO TB_COBRANCA (CODIGO, VALOR) VALUES (1, 1.0);